package com.entity;
// Generated 15-Sep-2019 12:21:04 by Hibernate Tools 4.3.1



/**
 * Booking generated by hbm2java
 */
public class Booking  implements java.io.Serializable {


     private Integer id;
     private String catagory;
     private String dname;
     private String name;
     private String date;
     private String time;
     private String fees;
     private Integer mobile;

    public Booking() {
    }

    public Booking(String catagory, String dname, String name, String date, String time, String fees, Integer mobile) {
       this.catagory = catagory;
       this.dname = dname;
       this.name = name;
       this.date = date;
       this.time = time;
       this.fees = fees;
       this.mobile = mobile;
    }

    public Booking(String catagory, String dname, String name, String date, String time, String fees) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCatagory() {
        return this.catagory;
    }
    
    public void setCatagory(String catagory) {
        this.catagory = catagory;
    }
    public String getDname() {
        return this.dname;
    }
    
    public void setDname(String dname) {
        this.dname = dname;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }
    public String getFees() {
        return this.fees;
    }
    
    public void setFees(String fees) {
        this.fees = fees;
    }
    public Integer getMobile() {
        return this.mobile;
    }
    
    public void setMobile(Integer mobile) {
        this.mobile = mobile;
    }




}


